describe("copilot-lualine.colors", function()
    local colors = require("copilot-lualine.colors")

    describe("name_to_hex", function()
        it("converts standard color names to hex", function()
            assert.are.equal("#FF0000", colors.name_to_hex("red"))
            assert.are.equal("#00FF00", colors.name_to_hex("green"))
            assert.are.equal("#0000FF", colors.name_to_hex("blue"))
            assert.are.equal("#000000", colors.name_to_hex("black"))
            assert.are.equal("#FFFFFF", colors.name_to_hex("white"))
        end)

        it("is case-insensitive", function()
            assert.are.equal("#FF0000", colors.name_to_hex("Red"))
            assert.are.equal("#FF0000", colors.name_to_hex("RED"))
            assert.are.equal("#00FF00", colors.name_to_hex("GREEN"))
        end)

        it("converts nvim color names to hex", function()
            assert.are.equal("#004C73", colors.name_to_hex("NvimDarkBlue"))
            assert.are.equal("#A6DBFF", colors.name_to_hex("NvimLightBlue"))
            assert.are.equal("#005523", colors.name_to_hex("NvimDarkGreen"))
        end)

        it("returns nil for unknown names", function()
            assert.is_nil(colors.name_to_hex("notacolor"))
            assert.is_nil(colors.name_to_hex("foobar"))
        end)
    end)

    describe("num_to_hex", function()
        it("converts 0 to #000000", function()
            assert.are.equal("#000000", colors.num_to_hex(0))
        end)

        it("converts positive numbers to hex", function()
            assert.are.equal("#FF0000", colors.num_to_hex(0xFF0000))
            assert.are.equal("#00FF00", colors.num_to_hex(0x00FF00))
            assert.are.equal("#0000FF", colors.num_to_hex(0x0000FF))
            assert.are.equal("#FFFFFF", colors.num_to_hex(0xFFFFFF))
        end)

        it("returns nil for nil input", function()
            assert.is_nil(colors.num_to_hex(nil))
        end)
    end)
end)
